version: "3"
services:
  app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always  
    ports:
      - 3000:3000

 

  socket:
    build:
      context: .
      dockerfile: ws/Dockerfile
    restart: always  
    ports:
      - 2000:2000
    
    env_file:
      - ./ws/.env 
     



  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always  
    ports:
      - 4000:4000  
    depends_on:
      - app
    env_file:
      - ./server/.env
   

  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "80:3000" 
  #   # volumes:
  #   #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Nginx configuration file
  #   depends_on:
  #     - app
  #     - backend
  #     - socket
#     networks:
#       - app_network
# networks:
#   app_network:
#     driver: bridge    